{{- if .Values.filebrowser.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "locust-distributed.fullname" . }}-filebrowser
  labels:
    {{- include "locust-distributed.filebrowserLabels" . | nindent 4 }}
spec:
  type: {{ .Values.filebrowser.service.type }}
  ports:
    - port: {{ .Values.filebrowser.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "locust-distributed.filebrowserSelectorLabels" . | nindent 4 }}
{{- end }}
