{{- if .Values.filebrowser.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "locust-distributed.fullname" . }}-filebrowser
  labels:
    {{- include "locust-distributed.filebrowserLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.filebrowser.replicas }}
  selector:
    matchLabels:
      {{- include "locust-distributed.filebrowserSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "locust-distributed.filebrowserSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "locust-distributed.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: filebrowser
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.filebrowser.image.repository }}:{{ .Values.filebrowser.image.tag }}"
          imagePullPolicy: {{ .Values.filebrowser.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: locust-scripts
              mountPath: /srv
          env:
            - name: FB_ROOT
              value: "/srv"
            - name: FB_DATABASE
              value: "/srv/.filebrowser.db"
            - name: FB_PORT
              value: "8080"
          resources:
            {{- toYaml .Values.filebrowser.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: locust-scripts
          {{- if .Values.storage.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "locust-distributed.fullname" . }}-storage
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
